services:  
  mysql_member:
    container_name: mysql_member
    restart: always
    image: mysql:8.0.40
    volumes:
      - mysql_member:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: member
    expose:
      - "3306"
    networks:
      - moeum

  mysql_music:
    container_name: mysql_music
    restart: always
    image: mysql:8.0.40
    volumes:
      - mysql_music:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: music
    expose:
      - "3306"
    networks:
      - moeum

  mysql_rec:
    container_name: mysql_rec
    restart: always
    image: mysql:8.0.40
    volumes:
      - mysql_rec:/var/lib/mysql
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: rec
    expose:
      - "3306"
    networks:
      - moeum

  mongo_music:
    container_name: mongo_music
    restart: always
    image: mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - mongo_music:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: music
    expose:
      - "27017"
    networks:
      - moeum

  redis_gateway:
    container_name: redis_gateway
    restart: always
    image: redis:7.4.1-alpine
    expose:
      - "6379"
    command: ["redis-server"]
    networks:
      - moeum

  redis_member:
    container_name: redis_member
    restart: always
    image: redis:7.4.1-alpine
    expose:
      - "6379"
    command: ["redis-server"]
    networks:
      - moeum
      
  redis_music:
    container_name: redis_music
    restart: always
    image: redis:7.4.1-alpine
    expose:
      - "6379"
    command: ["redis-server"]
    networks:
      - moeum

  redis_rec:
    container_name: redis_rec
    restart: always
    image: redis:7.4.1-alpine
    expose:
      - "6379"
    command: ["redis-server"]
    networks:
      - moeum
  
  rabbitmq:
    container_name: moeum_rabbitmq
    restart: always
    image: rabbitmq:4.0.3-management-alpine
    expose:
      - "5672"
    networks:
      - moeum

  gateway:
    container_name: moeum_gateway
    restart: always
    build: ./backend/gateway
    expose:
      - "8080"
    networks:
      - moeum

  member:
    container_name: moeum_member
    restart: always
    build: ./backend/member
    expose:
      - "8081"
    networks:
      - moeum

  music:
    container_name: moeum_music
    restart: always
    build: ./backend/music
    expose:
      - "8082"
    networks:
      - moeum

  # rec:
  #   container_name: moeum_rec
  #   restart: always
  #   build: ./backend/rec
  #   networks:
  #     - moeum

  client:
    container_name: moeum_client
    restart: always
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - moeum
  
volumes:
  mysql_member:
  mysql_music:
  mysql_rec:
  mongo_music:

networks:
  moeum:
    driver: bridge