services:
  mysql_member:
    container_name: mysql_member
    restart: always
    image: mysql:8.0.39
    volumes:
      - 'mysql_member:/var/lib/mysql'
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_TCP_PORT: 3310
    expose:
      - "3310"
    networks:
      - moeum

  mysql_music:
    container_name: mysql_music
    restart: always
    image: mysql:8.0.39
    volumes:
      - 'mysql_music:/var/lib/mysql'
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_TCP_PORT: 3311
    expose:
      - "3311"
    networks:
      - moeum

  mongo_music:
    container_name: mongo_music
    restart: always
    image: mongodb/mongodb-community-server:7.0-ubi8
    volumes:
      - 'mongo_music:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - "27017"
    networks:
      - moeum

  mysql_rec:
    container_name: mysql_rec
    restart: always
    image: mysql:8.0.39
    volumes:
      - 'mysql_rec:/var/lib/mysql'
    environment:
      TZ: Asia/Seoul
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_TCP_PORT: 3313
    expose:
      - "3313"
    networks:
      - moeum

  gateway:
    container_name: moeum_gateway
    restart: always
    build: ./backend/gateway
    networks:
      - moeum

  member:
    container_name: moeum_member
    restart: always
    build: ./backend/member
    networks:
      - moeum

  music:
    container_name: moeum_music
    restart: always
    build: ./backend/music
    networks:
      - moeum

  rec:
    container_name: moeum_rec
    restart: always
    build: ./backend/rec
    networks:
      - moeum

  client:
    container_name: moeum_client
    restart: always
    build: ./frontend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - moeum
  
  volumes:
    mysql_member:
    mysql_music:
    mysql_rec:
    mongo_music:

  network:
    moeum:
      driver: bridge