spring:
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: k11d203.p.ssafy.io:8081
          predicates:
            - Path=/members/**
          metadata:
            health-check-url: /actuator/health

        - id: settings-service
          uri: k11d203.p.ssafy.io:8082
          predicates:
            - Path=/musics/**
          metadata:
            health-check-url: /actuator/health

        - id: music-service
          uri: k11d203.p.ssafy.io:8084
          predicates:
            - Path=/musics/**
          metadata:
            health-check-url: /actuator/health

        - id: player-service
          uri: k11d203.p.ssafy.io:8085
          predicates:
            - Path=/player/**
          metadata:
            health-check-url: /actuator/health

        - id: history-service
          uri: k11d203.p.ssafy.io:8085
          predicates:
            - Path=/history/**
          metadata:
            health-check-url: /actuator/health

        - id: recommendations-service
          uri: k11d203.p.ssafy.io:8086
          predicates:
            - Path=/recommendations/**
          metadata:
            health-check-url: /actuator/health
service:
  url:
    member: http://52.78.65.114:8081
    music: http://52.78.65.114:8084
    player: http://52.78.65.114:8085
    history: http://52.78.65.114:8085
    settings: http://52.78.65.114:8081
    recommendations: http://52.78.65.114:8086