spring:
  datasource:
    url: jdbc:mysql://k11d203.p.ssafy.io:3306/moeum_setting?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000

  redis:
    host: k11d203.p.ssafy.io
    port: 6379
    lettuce:
      pool:
        max-active: 20
        max-idle: 16
        min-idle: 4