spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-music:3306/music?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
  rabbitmq:
    host: moeum-rabbitmq
    port: 5672

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: redis-music
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
    mongodb:
      host: mongo-music
      port: 27017
      database: music
      authentication-database: admin
      auto-index-creation: true
      write-concern: NORMAL