spring:
  config:
    import: classpath:application-secret.yml
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/moeum_rec?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
  rabbitmq:
    host: localhost
    port: 5672

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 8
          min-idle: 2
    mongodb:
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@ssafy.ngivl.mongodb.net/S11P31D203?authSource=admin
      database: S11P31D203
      port: 27017
      authentication-database: admin
      auto-index-creation: true
      write-concern: NORMAL