spring:
  datasource:
    url: jdbc:mysql://mysql_member:3306/member?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      idle-timeout: 300000
  rabbitmq:
    host: moeum_rabbitmq
    port: 5672

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  data:
    redis:
      host: redis_member
      port: 6379
      lettuce:
        pool:
          max-active: 20
          max-idle: 16
          min-idle: 4